# -*- coding: utf-8 -*-
"""BookReccomendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1meIt1zMhgEW41foSLBopJkfLZuSpyFOc
"""

import numpy as np
import sklearn
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD
from sklearn import pipeline

data_books = pd.read_csv('/content/drive/MyDrive/Datasets/Books.csv', low_memory=False, encoding="latin-1") # Encode in Latin 1 and set low_memory to false for special characters and mixed column types
data_ratings = pd.read_csv('/content/drive/MyDrive/Datasets/Ratings.csv')

data_ratings = data_ratings[data_ratings["Book-Rating"] != 0].copy()

top_users = data_ratings['User-ID'].value_counts().head(1000).index # Set-like list of selected users
top_books = data_ratings['ISBN'].value_counts().head(2000).index # Set-like list of selected Books

data_ratings = data_ratings[
    data_ratings['User-ID'].isin(top_users) &
    data_ratings['ISBN'].isin(top_books)
].copy()

print("Filtered ratings shape:", data_ratings.shape)
print("Unique books:", data_ratings['ISBN'].nunique())
print("Unique users:", data_ratings['User-ID'].nunique())

# 2. Setup ID Mappings
books_uniques = np.unique(data_ratings.ISBN.values)
users_uniques = np.unique(data_ratings['User-ID'].values)

books_dict_real_ref = {res: idx for idx, res in enumerate(books_uniques)}
books_dict_ref_real = {idx: res for idx, res in enumerate(books_uniques)}
users_dict_real_ref = {res: idx for idx, res in enumerate(users_uniques)}

ratings_mat = np.zeros(shape=(len(books_uniques), len(users_uniques)), dtype=np.float32)

# Rows = Books, Cols = Users
for user_id, isbn, rating in data_ratings[['User-ID', 'ISBN', 'Book-Rating']].itertuples(index=False, name=None):
    ref_u = users_dict_real_ref[user_id]
    ref_b = books_dict_real_ref[isbn]
    ratings_mat[ref_b, ref_u] = rating

# Means Centering (Fixing "0" Rating)
book_means = np.array(
    [np.mean(row[row > 0]) if np.any(row > 0)
    else 0 for row in ratings_mat],
    dtype=np.float32
)
ratings_mat_centered = ratings_mat - book_means.reshape(-1, 1)
ratings_mat_centered[ratings_mat == 0] = 0

U, S, V = np.linalg.svd(ratings_mat_centered, full_matrices=False)
print("SVD singular values:", S)
print("U matrix:", U)
print("V^T matrix:", V)

S_square = np.square(S)
p = S_square / np.sum(S_square)
svd_entropy = -np.sum(p[p > 0] * np.log2(p[p > 0]))

print("SVD Entropy:", svd_entropy)

energy = np.sum(S_square[:2]) / np.sum(S_square)
print(energy)

k = 50
book_latent = U[:, :k] * S[:k]

book_variability = np.array(
    [np.var(row[row > 0]) if np.any(row > 0) and len(row[row > 0]) > 1 else 0
     for row in ratings_mat],
    dtype=np.float32
)

# Weight Recommendation by Information Richness
# Combining the Latent Similarity with Entropy so that highly informative books influence recommendations score
def get_recommendations_info_weighted(latent_matrix, book_real_id, book_variability, top_n=10):
    ref_id = books_dict_real_ref[book_real_id]
    book_vector = latent_matrix[ref_id, :].reshape(1, -1)

    scores = cosine_similarity(book_vector, latent_matrix).flatten()
    weights = 1 + book_variability / (book_variability.max() + 1e-8)
    weighted_scores = scores * weights
    top_indices = np.argsort(weighted_scores)[::-1]

    return top_indices[1:top_n+1]

k = 50
search_isbn = books_uniques[0]
reduced_U = U[:, :k]


book_entropies = np.array([np.var(row[row > 0]) if np.any(row > 0) and len(row[row > 0]) > 1 else 0 for row in ratings_mat], dtype=np.float32)

top_indices = get_recommendations_info_weighted(reduced_U, search_isbn, book_variability, top_n=10)

# Print readable titles
search_title = data_books.loc[data_books['ISBN'] == search_isbn, 'Book-Title']
search_title = search_title.values[0] if len(search_title) else f"(title not found for ISBN {search_isbn})"
print(f"Books similar to: {search_title}\n" + "-"*30)

for idx in top_indices:
    real_isbn = books_dict_ref_real[idx]
    title = data_books.loc[data_books['ISBN'] == real_isbn, 'Book-Title']
    title = title.values[0] if len(title) else "(title missing)"
    print(f"ISBN {real_isbn}: {title}")
